FROM alpine:latest
RUN apk add git wget curl
RUN wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
RUN unzip terraform* -d /usr/bin
RUN rm *terraform*.zip
#TODO add az cli, ansible